### PR TITLE
Remove unnecessary if statements

### PR DESCRIPTION
**Pull request by meysammahfouzi**

### CODE REVIEW

**Comment by ShawnClake** [comment]
Looks good to me, thanks for the pull request. I'll merge this in for the next release.

**Comment by Teranode** [comment]
pls re-review >_> the statements are missing `;` after them

**Comment by Teranode** [comment]
also change Friends to Friend since its one Model

**Comment by ShawnClake** [comment]
Good catch and fix with the semi colons.

For the 'Friends' catch, I suspect he based his pull request off of the current release on the master branch where the model is in fact named 'Friends'. That was a naming error on my part and that has been fixed in the pre-release branch. 

When I merge this, I will change it if it hasn't been already.

**Pull request closed without merging**
